# -*- coding: utf-8 -*-
"""Anidya_Nag_005_IR_Lab_1(28_01_22).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ctkuAhq4tCTnoQzNOZaxZxMylgifb0Ae
"""

#ANINDYA NAG
#Roll:005

import re
from collections import Counter

def count_words(path):
  with open(path, encoding='utf-8') as file:
    total_words = re.findall(r"[0-9a-zA-z-']+", file.read())
    total_words = [word.upper() for word in total_words]
    print('\nTotal Words:', len(total_words))

    word_counts = Counter()
    for word in total_words:
      word_counts[word] +=1
    
    print('\nTop 10 Words:')
    for word in word_counts.most_common(10):
      print(word[0], '\t', word[1])

count_words('Anindya_lab1.txt')